title: "Toon Van Kimmenade"
url: "https://github.com/toonvank"
baseurl: "/toonvank.github.io"
domain: toonvank.github.io
author: "Toon Van Kimmenade"
description: "Toon Van Kimmenade's personal website"
og_image: "./pxl-logo.png"
summary: "Toon Van Kimmenade's personal website"

markdown: kramdown
ins_logo: "./pxl-logo.png"

tracking_id: G-H6CDESNR1E

footer: yes
#footer_url: "https://github.com/toonvank"
footer_text: "Theme by <a href='https://github.com/ankitsultana/researcher'>Ankit Sultana</a>"
remote_theme: ankitsultana/researcher@gem

favicon_location : "./favicon.ico"
ins_url: "https://www.pxl.be/"

sass:
    style: compressed
    sass_dir: _sass

kramdown:
  enable_toc: true


nav:
 - name: "about"
   link: ""
# - name: "Resume"
#   link: "resume.pdf"
 - name: "contact"
   link: "contact"
 - name: "blog"
   link: https://blog.toonvank.online/
 - name: "design"
   link: "design"