title: Toon Van Kimmenade
url: "http://toonvank.github.io"
baseurl: "/toonvank.github.io"
domain: toonvank.github.io

markdown: kramdown
ins_logo: "./pxl-logo.png"

tracking_id: G-H6CDESNR1E

footer: yes
#footer_url: "https://github.com/toonvank"
footer_text: "<a href='https://github.com/toonvank'>My GitHub</a>. Theme by <a href='https://github.com/ankitsultana/researcher'>Ankit Sultana</a>"
remote_theme: ankitsultana/researcher@gem

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
# - name: "Resume"
#   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Blog"
   link: https://blog.toonvank.online/